[[main]]
  name = "GitHub"
  url = "https://github.com/tymyrddin"
  weight = 10

[[social]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/nina-barzh"
  weight = 20

[[social]]
  name = "Twitter"
  url = "https://twitter.com/TyMyrddin"
  weight = 30
